### ISSUE TITLE
Validation de script avec du code CSS

### ISSUE THREAD

**Issue by cedric-demongivert** [cedric-demongivert/babel#11]
Pour vérifier que l'arbre syntaxique est valide on pourrait s'inspirer du css non ?

Type :

root > function sort (1+) > return

pour vérifier :

...

function sort(arg) { return; }

...

ou des trucs comme :

root > function sort + function plop

pour vérifier :

...

function sort(...) { ... }

function plop(...) { ... }

...

etc...

**Comment by raphael-leger** [comment]
Bonne idée :+1:

**Comment by cedric-demongivert** [comment]
C'est done !!!!
