### ISSUE TITLE
Créer le système d’exécution pas à pas.

### ISSUE THREAD

**Issue by cedric-demongivert** [cedric-demongivert/babel#6]
- Exécution pas à pas maximal.
- Exécution par expression mathématique.
- Exécution par ligne.
- Exécution par structure de contrôle.

**Comment by cedric-demongivert** [comment]
Pour tester par ligne, chaque noeud sauvegarde sa position dans le script : Tant que la ligne ne change pas -> on continue d'éxécuter

Pour stopper en fonction du noeud actuel, l'arbre sauvegarde les boucles, les appels de fonctions etc : Tant que type de node authorisé -> on continue d'éxécuter (voir variable stateStack)

Penser a mettre un garde fou pour les boucles infinies.

**Comment by cedric-demongivert** [comment]
Objet helper dans ASTRequest (Node)

**Comment by cedric-demongivert** [comment]
Bon ! J'ai écrit la base je vous laisse la suite.

**Comment by raphael-leger** [comment]
N'a été demandé que le pas-à-pas instruction par instruction et c'est fait.
Donc je close le ticket et on en ouvrira d'autres si y'a besoin de plus d'options ;)
